workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS IPA
        script: |
          flutter build ipa --export-options-plist=/dev/null || true
          cd build/ios/archive
          xcodebuild -exportArchive \
            -archivePath Runner.xcarchive \
            -exportPath . \
            -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <false/>
          </dict>
          </plist>') || echo "Export failed but continuing..."
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
